package main

import (
	"path/filepath"
	"strings"
	"testing"

	"go/types"

	"golang.org/x/tools/go/packages"
)

func TestSliceExpr(t *testing.T) {
	tests := []struct {
		fieldPath string
		want      string
	}{
		{"x.S", "x.S"},
		{"*x.Child", "(*x.Child)"},
		{"x.Field", "x.Field"},
	}
	for _, tt := range tests {
		got := sliceExpr(tt.fieldPath)
		if got != tt.want {
			t.Errorf("sliceExpr(%q) = %q, want %q", tt.fieldPath, got, tt.want)
		}
	}
}

func TestZeroValue(t *testing.T) {
	tests := []struct {
		t    types.Type
		want string
	}{
		{types.Typ[types.Int], "0"},
		{types.Typ[types.Int64], "0"},
		{types.Typ[types.String], `""`},
		{types.Typ[types.Bool], "false"},
		{types.Typ[types.Float64], "0"},
		{types.NewPointer(types.Typ[types.Int]), "nil"},
		{types.NewSlice(types.Typ[types.Int]), "nil"},
		{types.NewMap(types.Typ[types.String], types.Typ[types.Int]), "nil"},
	}
	for _, tt := range tests {
		got := zeroValue(tt.t)
		if got != tt.want {
			t.Errorf("zeroValue(%v) = %q, want %q", tt.t, got, tt.want)
		}
	}
}

func TestGenerateResetExpr(t *testing.T) {
	generating := map[string]bool{}

	t.Run("basic types", func(t *testing.T) {
		got := generateResetExpr("x.N", types.Typ[types.Int], generating, true)
		if want := "x.N = 0"; got != want {
			t.Errorf("got %q, want %q", got, want)
		}
	})

	t.Run("slice", func(t *testing.T) {
		got := generateResetExpr("x.S", types.NewSlice(types.Typ[types.Int]), generating, true)
		if want := "x.S = x.S[:0]"; got != want {
			t.Errorf("got %q, want %q", got, want)
		}
	})

	t.Run("map", func(t *testing.T) {
		got := generateResetExpr("x.M", types.NewMap(types.Typ[types.String], types.Typ[types.String]), generating, true)
		if want := "clear(x.M)"; got != want {
			t.Errorf("got %q, want %q", got, want)
		}
	})

	t.Run("pointer to primitive", func(t *testing.T) {
		got := generateResetExpr("x.P", types.NewPointer(types.Typ[types.String]), generating, true)
		if !strings.Contains(got, "if x.P != nil") || !strings.Contains(got, `*x.P = ""`) {
			t.Errorf("expected nil check and dereference, got %q", got)
		}
	})
}

func TestFindResetStructsAndGenerate(t *testing.T) {
	moduleRoot, err := filepath.Abs(".")
	if err != nil {
		t.Fatalf("abs: %v", err)
	}

	cfg := &packages.Config{
		Dir:  moduleRoot,
		Mode: packages.NeedName | packages.NeedFiles | packages.NeedSyntax | packages.NeedTypes | packages.NeedTypesInfo,
	}

	pkgs, err := packages.Load(cfg, "github.com/IgorRAzumov/go-link-shorter/internal/domain/model")
	if err != nil {
		t.Fatalf("packages.Load: %v", err)
	}
	if len(pkgs) != 1 {
		t.Fatalf("expected 1 package, got %d", len(pkgs))
	}
	pkg := pkgs[0]
	if len(pkg.Errors) > 0 {
		t.Fatalf("package errors: %v", pkg.Errors)
	}

	structs := findResetStructs(pkg)
	if len(structs) == 0 {
		t.Fatal("expected at least one reset struct in model package")
	}

	var found bool
	for _, s := range structs {
		if s.Name == "ResetableStruct" {
			found = true
			fieldNames := make(map[string]bool)
			for _, f := range s.Fields {
				fieldNames[f.Name] = true
			}
			for _, name := range []string{"IntVal", "StrVal", "StrPtr", "IntSlice", "StrMap", "Child"} {
				if !fieldNames[name] {
					t.Errorf("ResetableStruct missing field %q", name)
				}
			}
			break
		}
	}
	if !found {
		t.Error("ResetableStruct not found in reset structs")
	}

	content := generateResetFile(pkg, structs)
	if len(content) == 0 {
		t.Fatal("generateResetFile returned empty content")
	}

	gen := string(content)
	checks := []string{
		"// Code generated by cmd/reset. DO NOT EDIT.",
		"package model",
		"func (x *ResetableStruct) Reset()",
		"if x == nil",
		"x.IntVal = 0",
		`x.StrVal = ""`,
		"x.IntSlice = x.IntSlice[:0]",
		"clear(x.StrMap)",
		"x.Child.Reset()",
	}
	for _, want := range checks {
		if !strings.Contains(gen, want) {
			t.Errorf("generated code missing %q", want)
		}
	}
}
