package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/token"
	"go/types"
	"os"
	"path/filepath"
	"strings"

	"golang.org/x/tools/go/packages"
)

const generateResetComment = "// generate:reset"

func main() {
	rootDir := "."
	if len(os.Args) > 1 {
		rootDir = os.Args[1]
	}

	absRoot, err := filepath.Abs(rootDir)
	if err != nil {
		_, _ = fmt.Fprintf(os.Stderr, "failed to get absolute path: %v\n", err)
		os.Exit(1)
	}

	cfg := &packages.Config{
		Dir:  absRoot,
		Mode: packages.NeedName | packages.NeedFiles | packages.NeedSyntax | packages.NeedTypes | packages.NeedTypesInfo,
	}

	pkgs, err := packages.Load(cfg, "./...")
	if err != nil {
		_, _ = fmt.Fprintf(os.Stderr, "failed to load packages: %v\n", err)
		os.Exit(1)
	}

	if packages.PrintErrors(pkgs) > 0 {
		os.Exit(1)
	}

	for _, pkg := range pkgs {
		if pkg.Name == "" || len(pkg.GoFiles) == 0 {
			continue
		}

		structs := findResetStructs(pkg)
		if len(structs) == 0 {
			continue
		}

		content := generateResetFile(pkg, structs)

		pkgDir := filepath.Dir(pkg.GoFiles[0])
		outPath := filepath.Join(pkgDir, "reset.gen.go")
		if err := os.WriteFile(outPath, content, 0o644); err != nil {
			_, _ = fmt.Fprintf(os.Stderr, "failed to write %s: %v\n", outPath, err)
			os.Exit(1)
		}
		fmt.Printf("Generated %s\n", outPath)
	}
}

type resetStruct struct {
	Name   string
	Fields []resetField
}

type resetField struct {
	Name string
	Type types.Type
}

func findResetStructs(pkg *packages.Package) []resetStruct {
	var result []resetStruct
	info := pkg.TypesInfo

	for _, f := range pkg.Syntax {
		for _, decl := range f.Decls {
			genDecl, ok := decl.(*ast.GenDecl)
			if !ok || genDecl.Tok != token.TYPE {
				continue
			}

			for _, spec := range genDecl.Specs {
				typeSpec, ok := spec.(*ast.TypeSpec)
				if !ok {
					continue
				}

				if !hasGenerateResetComment(genDecl) {
					continue
				}

				structType, ok := typeSpec.Type.(*ast.StructType)
				if !ok {
					continue
				}

				fields := extractFields(info, structType)
				result = append(result, resetStruct{
					Name:   typeSpec.Name.Name,
					Fields: fields,
				})
			}
		}
	}
	return result
}

func structNames(structs []resetStruct) map[string]bool {
	names := make(map[string]bool)
	for _, s := range structs {
		names[s.Name] = true
	}
	return names
}

func hasGenerateResetComment(genDecl *ast.GenDecl) bool {
	doc := genDecl.Doc
	if doc == nil {
		return false
	}
	for _, c := range doc.List {
		if strings.TrimSpace(c.Text) == generateResetComment {
			return true
		}
	}
	return false
}

func extractFields(info *types.Info, structType *ast.StructType) []resetField {
	var fields []resetField
	for _, field := range structType.Fields.List {
		if len(field.Names) == 0 {
			continue
		}
		currentType := info.TypeOf(field.Type)
		if currentType == nil {
			continue
		}
		for _, name := range field.Names {
			fields = append(fields, resetField{
				Name: name.Name,
				Type: currentType,
			})
		}
	}
	return fields
}

func generateResetFile(pkg *packages.Package, structs []resetStruct) []byte {
	var buf bytes.Buffer

	buf.WriteString("// Code generated by cmd/reset. DO NOT EDIT.\n\n")
	buf.WriteString("package ")
	buf.WriteString(pkg.Name)
	buf.WriteString("\n\n")

	generating := structNames(structs)
	for _, s := range structs {
		generateResetMethod(&buf, s, generating)
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		_, _ = fmt.Fprintf(os.Stderr, "format error: %v\n", err)
		return buf.Bytes()
	}
	return formatted
}

func generateResetMethod(buf *bytes.Buffer, s resetStruct, generating map[string]bool) {
	buf.WriteString("func (x *")
	buf.WriteString(s.Name)
	buf.WriteString(") Reset() {\n")
	buf.WriteString("\tif x == nil {\n\t\treturn\n\t}\n\n")

	for _, f := range s.Fields {
		buf.WriteString("\t")
		buf.WriteString(generateResetExpr("x."+f.Name, f.Type, generating, true))
		buf.WriteString("\n")
	}

	buf.WriteString("}\n\n")
}

func generateResetExpr(fieldPath string, t types.Type, generating map[string]bool, forField bool) string {
	switch currentType := t.(type) {
	case *types.Pointer:
		elem := currentType.Elem()
		if isResettableStruct(elem, generating) {
			if forField {
				return fmt.Sprintf("if %s != nil {\n\t\t%s.Reset()\n\t}", fieldPath, fieldPath)
			}
			return fieldPath + ".Reset()"
		}
		inner := generateResetExpr("*"+fieldPath, elem, generating, false)
		if forField {
			return fmt.Sprintf("if %s != nil {\n\t\t%s\n\t}", fieldPath, inner)
		}
		return inner

	case *types.Slice:
		return fieldPath + " = " + sliceExpr(fieldPath) + "[:0]"

	case *types.Map:
		return "clear(" + fieldPath + ")"

	case *types.Array:
		return generateArrayReset(fieldPath, currentType)

	default:
		return fieldPath + " = " + zeroValue(currentType)
	}
}

func sliceExpr(fieldPath string) string {
	if strings.HasPrefix(fieldPath, "*") {
		return "(" + fieldPath + ")"
	}
	return fieldPath
}

func generateArrayReset(fieldPath string, arr *types.Array) string {
	return fieldPath + " = " + typeString(arr) + "{}"
}

func typeString(t types.Type) string {
	return types.TypeString(t, func(*types.Package) string { return "" })
}

func isResettableStruct(t types.Type, generating map[string]bool) bool {
	if named, ok := t.(*types.Named); ok && generating[named.Obj().Name()] {
		return true
	}
	newPointer := types.NewPointer(t)
	methodSet := types.NewMethodSet(newPointer)
	for i := 0; i < methodSet.Len(); i++ {
		if methodSet.At(i).Obj().Name() == "Reset" {
			return true
		}
	}
	return false
}

func basicZeroValue(k types.BasicKind) string {
	switch k {
	case types.Bool:
		return "false"
	case types.Int, types.Int8, types.Int16, types.Int32, types.Int64:
		return "0"
	case types.Uint, types.Uint8, types.Uint16, types.Uint32, types.Uint64, types.Uintptr:
		return "0"
	case types.Float32, types.Float64:
		return "0"
	case types.Complex64, types.Complex128:
		return "0"
	case types.String:
		return `""`
	case types.UnsafePointer:
		return "nil"
	default:
		return "nil"
	}
}

func zeroValue(t types.Type) string {
	switch underlying := t.Underlying().(type) {
	case *types.Basic:
		return basicZeroValue(underlying.Kind())
	case *types.Slice, *types.Map, *types.Pointer, *types.Signature, *types.Interface:
		return "nil"
	case *types.Struct, *types.Array:
		return typeString(t) + "{}"
	default:
		return "nil"
	}
}
