// Code generated by cmd/reset. DO NOT EDIT.

package model

func (x *ResetableStruct) Reset() {
	if x == nil {
		return
	}

	x.IntVal = 0
	x.StrVal = ""
	if x.StrPtr != nil {
		*x.StrPtr = ""
	}
	x.IntSlice = x.IntSlice[:0]
	clear(x.StrMap)
	if x.Child != nil {
		x.Child.Reset()
	}
}
